# -*- coding: utf-8 -*-
"""Hackersdobem-logica-290224.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btib5MLks9GyOnB9-z8ZN0ckTBxYIHkg
"""

# Aula grupo 9
#Exemplo de comversão de Notas para Conceito

# Entrada de dados:
nota = float(input("Digite a nota do aluno\n"))

#Processamento dos dados:
if(nota>9):
  print("Conceito Final: A")
elif(nota>=7):
    print("Conceito Final: B")
elif(nota>=6):
    print("Conceito Final: C")
elif(nota>=5):
  print("Conceito Final: D")
else:
  print("Conceito Final: F")

"""* Sem uso do comando while"""

# recebendo Nimero do Usuario
numero = input("digite um numero para o calculo de sua tabuada:\n")

#Convertendo numero para inteiro:
numero = int(numero)

# Exibindo a tabuada do Numero:
print(f"{numero} x 1 = {numero*1}")
print(f"{numero} x 2 = {numero*2}")
print(f"{numero} x 3 = {numero*3}")
print(f"{numero} x 4 = {numero*4}")
print(f"{numero} x 5 = {numero*5}")
print(f"{numero} x 6 = {numero*6}")
print(f"{numero} x 7 = {numero*7}")
print(f"{numero} x 8 = {numero*8}")
print(f"{numero} x 9 = {numero*9}")
print(f"{numero} x 10 = {numero*10}")

"""* Usando While"""

# recebendo Nimero do Usuario
numero = input("digite um numero para o calculo de sua tabuada:\n")
#Convertendo numero para inteiro:
numero = int(numero)
# Criando a variavel de controle do laço de repetição
contador = 1
while(contador<=10):
  #exibindo o valor da tabuada:
  print(f"{numero} x {contador} = { numero*contador}")
  contador = contador + 1

# Criando a variavel de comtrole do laço, contando 5 repetiçoes
contador = 1
# Criando uma variavel para acumular os valores das idades digitadas:
soma = 0
# Criando o laço de repetição para receber 5 idades e soma-las:
while(contador<=5):
  #Recebendo a indade do usuario
  idade = int(input(f"Digite a idade do usuaruio numero {contador}: "))
  #somando a idade do usuario ao valor atual da variavel acumulador
  soma = soma + idade
  # incrementando a variavel contador para controle do laço
  contador = contador + 1
# calculando a media das idades:
media = soma / (contador -1)
print(f"A média das idades digitadas é igual: {media}")

"""*Comando for"""

# Entrada DE DADOS
num = int(input("Digite um numeropara o calculo de sua tabuada: "))
print(f"\nCalculando a tabuada do numero {num}:  \n")
for i in range (1,11):
  print(f"{num} X {i} = {num*1}")





